"use client"

import { useEffect, useState } from "react"
import { Card } from "@/components/ui/Card"
import { User, CheckCircle2, XCircle, AlertTriangle, AlertCircle } from "lucide-react"
import { format } from "date-fns"

export type ScanResultStatus = "success" | "already_checked_in" | "expired" | "suspended" | "invalid_qr" | null

export interface ScanResultProps {
  member: any
  status: ScanResultStatus
  onClose: () => void
}

export function ScanResultModal({ member, status, onClose }: ScanResultProps) {
  const [progress, setProgress] = useState(100)
  
  // Auto-dismiss after 4 seconds
  useEffect(() => {
    if (!status) return

    const totalDuration = 4000
    const interval = 40 // update every 40ms
    const steps = totalDuration / interval
    const decrement = 100 / steps

    const timer = setInterval(() => {
      setProgress((prev) => {
        if (prev <= 0) {
          clearInterval(timer)
          return 0
        }
        return prev - decrement
      })
    }, interval)

    const dismissTimeout = setTimeout(() => {
      onClose()
    }, totalDuration)

    return () => {
      clearInterval(timer)
      clearTimeout(dismissTimeout)
    }
  }, [status, onClose])

  if (!status) return null

  // Config mapping for all result states
  const getConfig = () => {
    switch (status) {
      case "success":
        return {
          banner: "bg-[#10B981]",
          icon: <CheckCircle2 className="w-6 h-6 text-white" />,
          title: "CHECK-IN SUCCESSFUL",
          ring: "ring-[#10B981]",
        }
      case "already_checked_in":
        return {
          banner: "bg-[#F59E0B]",
          icon: <AlertTriangle className="w-6 h-6 text-white" />,
          title: "ALREADY CHECKED IN",
          ring: "ring-[#F59E0B]",
        }
      case "expired":
        return {
          banner: "bg-[#EF4444]",
          icon: <XCircle className="w-6 h-6 text-white" />,
          title: "MEMBERSHIP EXPIRED",
          ring: "ring-[#EF4444]",
        }
      case "suspended":
        return {
          banner: "bg-[#EF4444]",
          icon: <AlertCircle className="w-6 h-6 text-white" />,
          title: "ACCOUNT SUSPENDED",
          ring: "ring-[#EF4444]",
        }
      case "invalid_qr":
      default:
        return {
          banner: "bg-[#EF4444]",
          icon: <XCircle className="w-6 h-6 text-white" />,
          title: "INVALID QR CODE",
          ring: "ring-transparent",
        }
    }
  }

  const config = getConfig()

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-[100] flex items-center justify-center p-4 animate-in fade-in duration-200">
      <Card className="w-full max-w-[400px] p-0 overflow-hidden bg-bg-card border-white/10 shadow-2xl animate-in zoom-in-95 duration-300 relative">
        
        {/* Banner */}
        <div className={`h-16 w-full ${config.banner} flex items-center justify-center gap-3 px-4 shadow-inner`}>
          {config.icon}
          <span className="text-white font-bold tracking-widest text-sm">{config.title}</span>
        </div>

        {status === "invalid_qr" || !member ? (
           <div className="p-8 text-center flex flex-col items-center">
              <div className="w-20 h-20 rounded-full bg-input border border-white/10 flex items-center justify-center mb-4">
                 <AlertCircle className="w-8 h-8 text-muted" />
              </div>
              <h3 className="text-lg font-bold text-primary mb-2">Unknown Member</h3>
              <p className="text-secondary text-sm">This QR code was not found in the database. Ensure the code was generated by this system.</p>
           </div>
        ) : (
          <div className="p-8 flex flex-col items-center text-center">
            {/* Profile Photo */}
            <div className={`w-24 h-24 rounded-full p-1 ring-4 ${config.ring} bg-bg-card mb-4 relative -mt-16 shadow-xl`}>
              <div className="w-full h-full rounded-full bg-input/50 flex items-center justify-center overflow-hidden">
                {member.photo_url ? (
                  <img src={member.photo_url} alt={member.name} className="w-full h-full object-cover" />
                ) : (
                  <User className="w-10 h-10 text-muted" />
                )}
              </div>
            </div>

            <h2 className="text-2xl font-bold text-primary mb-1 tracking-tight">{member.name}</h2>
            <p className="text-secondary text-sm font-medium uppercase tracking-wider mb-6">
              {member.membership_type.replace('_', ' ')} Member
            </p>

            {/* Details Grid */}
            <div className="w-full bg-input border border-white/5 rounded-xl p-4 grid gap-3 text-left">
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted tracking-wide uppercase text-[11px]">Valid Thru</span>
                <span className="text-primary font-medium font-mono">{format(new Date(member.end_date), 'MMM d, yyyy')}</span>
              </div>
              
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted tracking-wide uppercase text-[11px]">Status</span>
                <span className="flex items-center gap-2">
                  <span className={`w-2 h-2 rounded-full ${member.status === 'active' ? 'bg-[#10B981]' : member.status === 'suspended' ? 'bg-[#F59E0B]' : 'bg-[#EF4444]'}`}></span>
                  <span className="text-primary capitalize">{member.status}</span>
                </span>
              </div>

               <div className="flex justify-between items-center text-sm">
                <span className="text-muted tracking-wide uppercase text-[11px]">Total Visits</span>
                <span className="text-primary font-medium">
                  {member.attendance ? member.attendance.length + (status === 'success' ? 1 : 0) : (status === 'success' ? 1 : 0)}
                 </span>
              </div>
            </div>
          </div>
        )}

        {/* Dismissal Progress Bar */}
        <div className="h-1.5 w-full bg-white/5 absolute bottom-0 left-0">
          <div 
            className="h-full bg-white/30 transition-all duration-[40ms] ease-linear"
            style={{ width: `${progress}%` }}
          />
        </div>
      </Card>
    </div>
  )
}
